
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Medac
 */
public class Ventana3 extends javax.swing.JFrame {
      Jugador jugador;
    /**
     * Creates new form Ventana3
     */
    public Ventana3() {
        initComponents();
    }
   public Ventana3(Jugador jugador){
       initComponents();
       this.jugador=jugador;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("INTRODUCE EL VALOR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        Object[]valores={"simple","doble","triple"};
       int respuesta= JOptionPane.showOptionDialog(rootPane, "simple doble o triple", "Elige la opcion", 
               JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,valores,"simple"); 
       dispose();
        

           String puntos= jTextField1.getText();
                   System.out.println(puntos);
        switch(respuesta){
            case 0:
              comprobarValor(puntos,jugador,1);
                break;
            case 1:            
              comprobarValor(puntos,jugador,2);
                break;
            
            case 2:       
              comprobarValor(puntos,jugador,3);
                break;
                
                
        }
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void comprobarValor(String puntos, Jugador jugador,int multiplicacion) {
          int puntosAnterior ;
        switch(puntos){
         
            case "centro":
             puntosAnterior  = jugador.getPuntuacion().get("centro");
            jugador.getPuntuacion().put("centro", puntosAnterior+multiplicacion);
            
            break;
            
            case " 20":
                  puntosAnterior  = jugador.getPuntuacion().get("20");
            jugador.getPuntuacion().put("20", puntosAnterior+multiplicacion);
              break;
              
              case " 19":
                  puntosAnterior  = jugador.getPuntuacion().get("19");
            jugador.getPuntuacion().put("19", puntosAnterior+multiplicacion);
              break;
              
              case " 18":
                  puntosAnterior  = jugador.getPuntuacion().get("18");
            jugador.getPuntuacion().put("18", puntosAnterior+multiplicacion);
              break;
              
              case " 17":
                  puntosAnterior  = jugador.getPuntuacion().get("17");
            jugador.getPuntuacion().put("17", puntosAnterior+=multiplicacion);
              break;
              
              case " 16":
                  puntosAnterior  = jugador.getPuntuacion().get("16");
            jugador.getPuntuacion().put("16", puntosAnterior+multiplicacion);
              break;
            
              case " 15":
                  puntosAnterior  = jugador.getPuntuacion().get("15");
            jugador.getPuntuacion().put("15", puntosAnterior+multiplicacion);
              break;
        }
        System.out.println(jugador.getPuntuacion());
        
    }
}
